### **Naive Bayes Machine Learning Algorithms Implementation**

In [1]:
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
X, y = load_iris(return_X_y=True)

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [6]:
## Since continuous values, using gaussian naive bayes
from sklearn.naive_bayes import GaussianNB

In [7]:
gnb = GaussianNB()

In [8]:
gnb.fit(X_train, y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)number of training samples observed in each class.","ndarray[float64](3,)","[34.,32.,39.]"
"class_prior_ class_prior_: ndarray of shape (n_classes,)probability of each class.","ndarray[float64](3,)","[0.32,0.3 ,0.37]"
"classes_ classes_: ndarray of shape (n_classes,)class labels known to the classifier.","ndarray[int32](3,)","[0,1,2]"
epsilon_ epsilon_: floatabsolute additive value to variances.,float64,3.225e-09
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,4
"theta_ theta_: ndarray of shape (n_classes, n_features)mean of each feature per class.","ndarray[float64](3, 4)","[[4.99,3.38,1.45,0.23], [5.92,2.76,4.2 ,1.31], [6.65,2.99,5.6 ,2.03]]"
"var_ var_: ndarray of shape (n_classes, n_features)Variance of each feature per class... versionadded:: 1.0","ndarray[float64](3, 4)","[[0.13,0.15,0.02,0.01], [0.28,0.12,0.23,0.04], [0.43,0.12,0.31,0.07]]"


In [9]:
y_pred = gnb.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [11]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


#### Assignment

In [12]:
import seaborn as sns

In [13]:
df = sns.load_dataset('tips')

In [14]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [15]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

Has some numerical and categorical values

Categorical values try to convert into ones and zeros

Try to predict anything, e.g., smoker(binary classification) or time

Take output as time and predict whether it is dinner or lunch

Try it, convert these features into one-hot encoded or label encoded

Said it should be converted into one-hot encoded, think why

One‑Hot Encoding avoids that by creating binary columns for each category:

sex_Female, sex_Male

smoker_Yes, smoker_No  
Each column is independent, so the model learns separate probabilities for each category without assuming order.

In [17]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [19]:
X = df.drop(columns=['time'])
y = df['time']

In [20]:
X

,total_bill,tip,sex,smoker,day,size
0,16.99,1.01,Female,No,Sun,2
1,10.34,1.66,Male,No,Sun,3
2,21.01,3.50,Male,No,Sun,3
3,23.68,3.31,Male,No,Sun,2
4,24.59,3.61,Female,No,Sun,4
...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,3
240,27.18,2.00,Female,Yes,Sat,2
241,22.67,2.00,Male,Yes,Sat,2
242,17.82,1.75,Male,No,Sat,2


In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [26]:
X_train.head()

,total_bill,tip,sex,smoker,day,size
115,17.31,3.50,Female,No,Sun,2
181,23.33,5.65,Male,Yes,Sun,2
225,16.27,2.50,Female,Yes,Fri,2
68,20.23,2.01,Male,No,Sat,2
104,20.92,4.08,Female,No,Sat,2


In [27]:
ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(drop='first'), [2, 3, 4])], remainder='passthrough')

In [28]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [29]:
X_test = ct.transform(X_test)

In [30]:
X_train

array([[ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 17.31,  3.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 23.33,  5.65,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 16.27,  2.5 ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.23,  2.01,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.92,  4.08,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 15.01,  2.09,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  7.25,  1.  ,  1.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 26.59,  3.41,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 24.52,  3.48,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 19.77,  2.  ,  4.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 28.15,  3.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 17.29,  2.71,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 19.65,  3.  ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 15.53,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.45,  3.  ,  4.  ],
       [ 1.  ,  1.  ,  0.

In [31]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [32]:
gnb.fit(X_train, y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)number of training samples observed in each class.","ndarray[float64](2,)","[132., 51.]"
"class_prior_ class_prior_: ndarray of shape (n_classes,)probability of each class.","ndarray[float64](2,)","[0.72,0.28]"
"classes_ classes_: ndarray of shape (n_classes,)class labels known to the classifier.","ndarray[<U6](2,)","['Dinner','Lunch']"
epsilon_ epsilon_: floatabsolute additive value to variances.,float64,7.82e-08
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,8
"theta_ theta_: ndarray of shape (n_classes, n_features)mean of each feature per class.","ndarray[float64](2, 8)","[[ 0.69, 0.4 , 0.5 ,...,21.58, 3.19, 2.64], [ 0.49, 0.35, 0. ,...,16.88, 2.79, 2.39]]"
"var_ var_: ndarray of shape (n_classes, n_features)Variance of each feature per class... versionadded:: 1.0","ndarray[float64](2, 8)","[[ 0.21, 0.24, 0.25,...,85.5 , 2.25, 0.77], [ 0.25, 0.23, 0. ,...,43.34, 1.5 , 1.1 ]]"


In [33]:
y_pred = gnb.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.9508196721311475
              precision    recall  f1-score   support

      Dinner       1.00      0.93      0.96        44
       Lunch       0.85      1.00      0.92        17

    accuracy                           0.95        61
   macro avg       0.93      0.97      0.94        61
weighted avg       0.96      0.95      0.95        61

[[41  3]
 [ 0 17]]
